
city_mapping = {
    '臺北市': 'taipei_city',
    '新北市': 'new_taipei_city',
    '基隆市': 'keelung_city',
    '連江縣': 'lianjiang_county',
    '桃園市': 'taoyuan_city',
    '新竹市': 'hsinchu_city',
    '新竹縣': 'hsinchu_county',
    '苗栗縣': 'miaoli_county',
    '台中市': 'taichung_city',
    '彰化縣': 'changhua_county',
    '雲林縣': 'yunlin_county',
    '嘉義縣': 'chiayi_county',
    '嘉義市': 'chiayi_city',
    '台南市': 'tainan_city',
    '南投縣': 'nantou_county',
    '高雄市': 'kaohsiung_city',
    '屏東縣': 'pingtung_county',
    '海南島': 'hainan_island',
    '澎湖縣': 'penghu_county',
    '金門縣': 'kinmen_county',
    '宜蘭縣': 'yilan_county',
    '花蓮縣': 'hualien_county',
    '台東縣': 'taitung_county',
    '其他': 'other',
    '線上': 'online',
    '待討論': 'tbd'
}

country_mapping = {
    "台灣": "Taiwan",
    "阿富汗": "Afghanistan",
    "奧蘭": "Aland Islands",
    "阿爾巴尼亞": "Albania",
    "阿爾及利亞": "Algeria",
    "美屬薩摩亞": "American Samoa",
    "安道爾": "Andorra",
    "安哥拉": "Angola",
    "安圭拉": "Anguilla",
    "南極洲": "Antarctica",
    "安地卡及巴布達": "Antigua and Barbuda",
    "阿根廷": "Argentina",
    "亞美尼亞": "Armenia",
    "阿魯巴": "Aruba",
    "澳大利亞": "Australia",
    "奧地利": "Austria",
    "亞塞拜然": "Azerbaijan",
    "巴哈馬": "Bahamas",
    "巴林": "Bahrain",
    "孟加拉": "Bangladesh",
    "巴貝多": "Barbados",
    "白俄羅斯": "Belarus",
    "比利時": "Belgium",
    "貝里斯": "Belize",
    "貝南": "Benin",
    "百慕達": "Bermuda",
    "不丹": "Bhutan",
    "玻利維亞": "Bolivia",
    "荷蘭加勒比區": "Bonaire, Sint Eustatius and Saba",
    "波士尼亞與赫塞哥維納": "Bosnia and Herzegovina",
    "波札那": "Botswana",
    "布韋島": "Bouvet Island",
    "巴西": "Brazil",
    "英屬印度洋領地": "British Indian Ocean Territory",
    "汶萊": "Brunei",
    "保加利亞": "Bulgaria",
    "布吉納法索": "Burkina Faso",
    "蒲隆地": "Burundi",
    "維德角": "Cabo Verde",
    "柬埔寨": "Cambodia",
    "喀麥隆": "Cameroon",
    "加拿大": "Canada",
    "開曼群島": "Cayman Islands",
    "中非": "Central African Republic",
    "查德": "Chad",
    "智利": "Chile",
    "中國": "China",
    "聖誕島": "Christmas Island",
    "科科斯（基林）群島": "Cocos (Keeling) Islands",
    "哥倫比亞": "Colombia",
    "葛摩": "Comoros",
    "剛果共和國": "Congo (Republic)",
    "剛果民主共和國": "Congo (Democratic Republic)",
    "庫克群島": "Cook Islands",
    "哥斯大黎加": "Costa Rica",
    "象牙海岸": "Cote d'Ivoire",
    "克羅埃西亞": "Croatia",
    "古巴": "Cuba",
    "古拉索": "Curaçao",
    "賽普勒斯": "Cyprus",
    "捷克": "Czech Republic",
    "丹麥": "Denmark",
    "吉布地": "Djibouti",
    "多米尼克": "Dominica",
    "多明尼加": "Dominican Republic",
    "厄瓜多": "Ecuador",
    "埃及": "Egypt",
    "薩爾瓦多": "El Salvador",
    "赤道幾內亞": "Equatorial Guinea",
    "厄利垂亞": "Eritrea",
    "愛沙尼亞": "Estonia",
    "史瓦帝尼": "Eswatini",
    "衣索比亞": "Ethiopia",
    "福克蘭群島": "Falkland Islands",
    "法羅群島": "Faroe Islands",
    "斐濟": "Fiji",
    "芬蘭": "Finland",
    "法國": "France",
    "法屬圭亞那": "French Guiana",
    "法屬玻里尼西亞": "French Polynesia",
    "法屬南部和南極領地": "French Southern and Antarctic Lands",
    "加彭": "Gabon",
    "甘比亞": "Gambia",
    "喬治亞": "Georgia",
    "德國": "Germany",
    "迦納": "Ghana",
    "直布羅陀": "Gibraltar",
    "希臘": "Greece",
    "格陵蘭": "Greenland",
    "格瑞那達": "Grenada",
    "瓜地洛普": "Guadeloupe",
    "關島": "Guam",
    "瓜地馬拉": "Guatemala",
    "根西": "Guernsey",
    "幾內亞": "Guinea",
    "幾內亞比索": "Guinea-Bissau",
    "蓋亞那": "Guyana",
    "海地": "Haiti",
    "赫德島和麥克唐納群島": "Heard Island and McDonald Islands",
    "梵蒂岡": "Vatican City",
    "宏都拉斯": "Honduras",
    "香港": "Hong Kong",
    "匈牙利": "Hungary",
    "冰島": "Iceland",
    "印度": "India",
    "印度尼西亞": "Indonesia",
    "伊朗": "Iran",
    "伊拉克": "Iraq",
    "愛爾蘭": "Ireland",
    "曼島": "Isle of Man",
    "以色列": "Israel",
    "義大利": "Italy",
    "牙買加": "Jamaica",
    "日本": "Japan",
    "澤西": "Jersey",
    "約旦": "Jordan",
    "哈薩克": "Kazakhstan",
    "肯亞": "Kenya",
    "吉里巴斯": "Kiribati",
    "北韓": "North Korea",
    "南韓": "South Korea",
    "科威特": "Kuwait",
    "吉爾吉斯": "Kyrgyzstan",
    "寮國": "Laos",
    "拉脫維亞": "Latvia",
    "黎巴嫩": "Lebanon",
    "賴索托": "Lesotho",
    "賴比瑞亞": "Liberia",
    "利比亞": "Libya",
    "列支敦斯登": "Liechtenstein",
    "立陶宛": "Lithuania",
    "盧森堡": "Luxembourg",
    "澳門": "Macau",
    "馬達加斯加": "Madagascar",
    "馬拉威": "Malawi",
    "馬來西亞": "Malaysia",
    "馬爾地夫": "Maldives",
    "馬利": "Mali",
    "馬爾他": "Malta",
    "馬紹爾群島": "Marshall Islands",
    "馬丁尼克": "Martinique",
    "茅利塔尼亞": "Mauritania",
    "模里西斯": "Mauritius",
    "馬約特": "Mayotte",
    "墨西哥": "Mexico",
    "密克羅尼西亞聯邦": "Micronesia",
    "摩爾多瓦": "Moldova",
    "摩納哥": "Monaco",
    "蒙古": "Mongolia",
    "蒙特內哥羅": "Montenegro",
    "蒙特塞拉特": "Montserrat",
    "摩洛哥": "Morocco",
    "莫三比克": "Mozambique",
    "緬甸": "Myanmar",
    "納米比亞": "Namibia",
    "諾魯": "Nauru",
    "尼泊爾": "Nepal",
    "荷蘭": "Netherlands",
    "新喀里多尼亞": "New Caledonia",
    "紐西蘭": "New Zealand",
    "尼加拉瓜": "Nicaragua",
    "尼日": "Niger",
    "奈及利亞": "Nigeria",
    "紐埃": "Niue",
    "諾福克島": "Norfolk Island",
    "北馬其頓": "North Macedonia",
    "北馬利安納群島": "Northern Mariana Islands",
    "挪威": "Norway",
    "阿曼": "Oman",
    "巴基斯坦": "Pakistan",
    "帛琉": "Palau",
    "巴勒斯坦": "Palestine",
    "巴拿馬": "Panama",
    "巴布亞紐幾內亞": "Papua New Guinea",
    "巴拉圭": "Paraguay",
    "秘魯": "Peru",
    "菲律賓": "Philippines",
    "皮特凱恩群島": "Pitcairn Islands",
    "波蘭": "Poland",
    "葡萄牙": "Portugal",
    "波多黎各": "Puerto Rico",
    "卡塔爾": "Qatar",
    "留尼旺": "Réunion",
    "羅馬尼亞": "Romania",
    "俄羅斯": "Russia",
    "盧旺達": "Rwanda",
    "聖赫勒拿、阿森松與新愛島": "Saint Helena, Ascension and Tristan da Cunha",
    "聖基茨與尼維斯": "Saint Kitts and Nevis",
    "聖露西亞": "Saint Lucia",
    "聖皮埃爾和密克隆": "Saint Pierre and Miquelon",
    "聖文森及格瑞那丁": "Saint Vincent and the Grenadines",
    "薩摩亞": "Samoa",
    "聖馬力諾": "San Marino",
    "聖多美與普林西比": "São Tomé and Príncipe",
    "沙烏地阿拉伯": "Saudi Arabia",
    "塞內加爾": "Senegal",
    "塞爾維亞": "Serbia",
    "塞舌爾": "Seychelles",
    "獅子山": "Sierra Leone",
    "新加坡": "Singapore",
    "聖馬力諾": "San Marino",
    "索馬利亞": "Somalia",
    "南非": "South Africa",
    "南喬治亞與南三明治群島": "South Georgia and the South Sandwich Islands",
    "韓國": "South Korea",
    "南蘇丹": "South Sudan",
    "西班牙": "Spain",
    "斯里蘭卡": "Sri Lanka",
    "蘇丹": "Sudan",
    "蘇里南": "Suriname",
    "斯瓦爾巴與揚馬延": "Svalbard and Jan Mayen",
    "斯威士蘭": "Swaziland",
    "瑞典": "Sweden",
    "瑞士": "Switzerland",
    "敘利亞": "Syria",
    "塔吉克": "Tajikistan",
    "坦尚尼亞": "Tanzania",
    "泰國": "Thailand",
    "多哥": "Togo",
    "托克勞": "Tokelau",
    "湯加": "Tonga",
    "特立尼達與多巴哥": "Trinidad and Tobago",
    "突尼西亞": "Tunisia",
    "土耳其": "Turkey",
    "土庫曼": "Turkmenistan",
    "圖瓦盧": "Tuvalu",
    "烏干達": "Uganda",
    "烏克蘭": "Ukraine",
    "阿聯酋": "United Arab Emirates",
    "英國": "United Kingdom",
    "美國": "United States",
    "烏拉圭": "Uruguay",
    "烏茲別克": "Uzbekistan",
    "瓦努阿圖": "Vanuatu",
    "梵蒂岡": "Vatican City",
    "委內瑞拉": "Venezuela",
    "越南": "Vietnam",
    "美屬薩摩亞": "American Samoa",
    "約旦": "Jordan",
    "也門": "Yemen",
    "尚比亞": "Zambia",
    "辛巴威": "Zimbabwe"
}

partnerEducationStep_mapping = {
    '高中':'high',
    '不設限':'other', 
    '大學以上':'university'
}

group_category_mapping = {
    '語言與文學': 'language',
    '數學與邏輯': 'math',
    '資訊與工程': 'computer-science',
    '人文社會': 'humanity',
    '自然科學': 'nature-science',
    '藝術': 'art',
    '教育': 'education',
    '生活': 'life',
    '運動/心理/醫學': 'health',
    '商業與社會創新': 'business',
    '綜合型學習資源': 'diversity',
    '學習/教學工具': 'learningtools'
}

group_type_mapping = {
    '讀書會': 'study_group',
    '工作坊':'workshop',
    '專案':'project',
    '競賽':'competition',
    '活動':'event',
    '社團':'club',
    '課程':'course',
    '實習':'internship',
    '其他':'other', 
}

motivation_mapping = {
    '好奇心驅動': 'driven_by_curiosity',
    '興趣熱情': 'interest_and_passion',
    '自我挑戰': 'self_challenge',
    '個人成長': 'personal_growth',
    '職涯發展': 'career_development',
    '升學或資格獲取': 'pursuing_education_or_qualifications',
    '社會認可': 'social_recognition',
    '探索可能性': 'exploring_possibilities',
    '應對未來': 'preparing_for_the_future',
    '創新發展': 'innovation_and_development',
    '實用需求': 'practical_needs',
    '受事件啟發': 'inspired_by_events',
    '人際連結': 'interpersonal_connections',
    '生活發生變化': 'life_changes',
    '影響社會': 'impact_on_society',
    '受群體影響': 'influenced_by_a_group',
    '其他': 'others'
}


strategy_mapping = {
    '資料蒐集/研究/分析': 'data_collection_research_analysis',  # 包含資料搜集、研究設計、數據分析等全流程
    '書籍閱讀': 'book_reading',
    '觀看影片': 'watching_videos',
    '聽Podcast': 'listening_to_podcasts',
    '考試': 'examinations',
    '參與競賽': 'participating_in_competitions',
    '找學伴共學': 'finding_study_partners',  # 更強調尋找學習夥伴的目的
    '參與社群': 'joining_communities',
    '找專家學者': 'consulting_experts_and_scholars',
    '做專案': 'doing_projects',  # 更強調專案的執行過程
    '發起行動': 'initiating_actions',
    '場域實習': 'field_internship',
    '舉辦活動或課程': 'organizing_events_or_courses',
    '參與活動或課程': 'attending_events_or_courses',
    '田野調查': 'field_research',
    '訪談': 'conducting_interviews',
    '問卷調查': 'conducting_surveys',
    '其他': 'others',
}


outcome_mapping = {
    '架設網站': 'building_websites',
    '經營社群媒體': 'managing_social_media',
    '撰寫研究報告': 'writing_research_reports',
    '藝術創作': 'artistic_creation',
    '發起專案或組織' : 'initiating_projects_or_organizations',
    '拍影片' : 'making_videos',
    '舉辦活動' : 'organizing_events',
    '開課' : 'teaching_courses',
    '參與競賽':'participating_in_competitions',
    '其他' : 'others',
}

qualifications_mapping = {
    '中低收入戶': 'low_income',
    '優惠價': 'discount', 
    '個人早鳥價':'personal',
    '2人團報價': 'double',
    '3人團報價': 'three',
    '4人團報價': 'four'
}