-- -- 插入 project 表
-- INSERT INTO "project" (
--     "user_id", 
--     "img_url", 
--     "topic", 
--     "project_description", 
--     "motivation", 
--     "motivation_description", 
--     "goal", 
--     "content", 
--     "strategy", 
--     "strategy_description", 
--     "resource_name", 
--     "resource_url", 
--     "outcome", 
--     "outcome_description", 
--     "is_public", 
--     "status", 
--     "created_by", 
--     "updated_by", 
--     "version"
-- ) VALUES (
--     1, 
--     'https://example.com/image.jpg', 
--     'AI for Healthcare', 
--     'This project aims to use AI to improve healthcare.', 
--     ARRAY['driven_by_curiosity'::motivation_t, 'career_development'::motivation_t], 
--     'Motivated by curiosity and career development.', 
--     'Develop an AI-powered healthcare tool', 
--     'Research and development on machine learning techniques for healthcare.', 
--     ARRAY['data_collection_research_analysis', 'others']::strategy_t[], 
--     'Discounts available for students in low-income regions.', 
--     ARRAY['Document 1', 'Document 2'], 
--     ARRAY['https://resource1.com', 'https://resource2.com'], 
--     ARRAY['building_websites'::outcome_t, 'teaching_courses'::outcome_t], 
--     'Focus on building AI models and teaching healthcare professionals.', 
--     true, 
--     'Ongoing', 
--     1, 
--     2, 
--     1
-- );

-- -- 插入 user_project 表
-- INSERT INTO "user_project" ("user_id", "project_id") VALUES (1, 1);

-- -- 插入 milestone 表
-- INSERT INTO "milestone" (
--     "project_id", 
--     "start_date", 
--     "end_date", 
--     "interval"
-- ) VALUES (
--     1, 
--     '2025-01-01', 
--     '2025-06-01', 
--     2
-- );


-- -- 插入 task 表
-- INSERT INTO "task" (
--     "milestone_id", 
--     "name", 
--     "description", 
--     "start_date", 
--     "end_date", 
--     "is_completed", 
--     "is_deleted"
-- ) VALUES (
--     1, 
--     'Research AI Algorithms', 
--     'Research different AI algorithms for healthcare application.', 
--     '2025-01-02', 
--     '2025-03-01', 
--     false, 
--     false
-- );

-- -- 插入 subtask 表
-- INSERT INTO "subtask" (
--     "task_id", 
--     "name", 
--     "days_of_week", 
--     "is_completed", 
--     "is_deleted"
-- ) VALUES (
--     1, 
--     'Gather Data', 
--     ARRAY['Monday'::day_enum, 'Wednesday'::day_enum, 'Friday'::day_enum], 
--     false, 
--     false
-- );

-- 插入 eligibility 表


-- -- 插入 project_marathon 表
-- INSERT INTO "project_marathon" (
--     "project_id", 
--     "marathon_id", 
--     "project_registration_date", 
--     "status", 
--     "feedback"
-- ) VALUES (
--     1, 
--     1, 
--     current_timestamp, 
--     'Pending', 
--     'Waiting for approval.'
-- );